version: 2.1
orbs:
  node: circleci/node@2.0.2

jobs:
  install-and-build:
    environment:
      SHORT_GIT_HASH: $(echo $CIRCLE_SHA1 | cut -c -7)
    executor:
      name: node/default
      tag: '12.16.2'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: 12.16.2
      - run: node --version
      - run: echo $SHORT_GIT_HASH

  docker-build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build docker image
          command: docker build .
   
workflows:
    standard-flow:
        jobs:
        - install-and-build
