version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  install-and-build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn build
  docker-build:
    executor:
      name: node/default
    steps:
      - docker build .
   
  
workflows:
    standard-flow:
        jobs:
        - install-and-build
        - docker-build:
            requires:
              - install-and-build
            branches:
              only: circleci-setup
