version: 2.1
orbs:
  node: circleci/node@2.0.2

jobs:
  install-and-build:
    executor:
      name: node/default
      tag: '12.16.2'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: 12.16.2
      - run: node --version

  docker-build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Export git commit hash as env variable
          command: echo 'export COMMIT_TAG=$(git rev-parse --short HEAD)' >> "$BASH_ENV"
      - run:
          name: Print git commit
          command: echo $COMMIT_TAG
      - run:
          name: Build docker image
          command: docker build . -t psergiopoli/pbot:$COMMIT_TAG
      - run:
          name: Docker login
          command: docker login --username=psergiopoli --password=$DOCKER_PASSWORD
      - run:
          name: Docker push
          command: docker push psergiopoli/pbot:$COMMIT_TAG
   
workflows:
    standard-flow:
        jobs:
        - install-and-build
        - docker-build:
            requires:
              - install-and-build
            filters:
              branches:
                only: master
